repos:
  # Python hooks
  - repo: local
    hooks:
      # Ruff for Python linting
      - id: ruff
        name: ruff (Python linting)
        entry: ruff check --fix
        language: python
        types_or: [python, pyi, jupyter]
        files: \.py$

      # Ruff for Python formatting
      - id: ruff-format
        name: ruff-format (Python formatting)
        entry: ruff format
        language: python
        types_or: [python, pyi, jupyter]
        files: \.py$

      # Mypy for Python type checks
      - id: mypy
        name: mypy (Python typing)
        entry: mypy .
        language: python
        types_or: [python, pyi]
        files: \.py$

      # Dependency checks for Python
      - id: check-python-dependencies
        name: Check Python dependencies
        entry: bash -c 'pipenv check --bare --quiet || (echo "Python dependencies check failed" && exit 1)'
        language: system
        files: ^Pipfile$

      # Radon checks for maintainability and difficulty
      - id: radon-check
        name: Radon Maintainability and Halstead Checks
        entry: |
          bash -c '
          radon mi -s {} --exclude "scratch" | grep -E " - [BCDEF] \(" && echo "Radon MI grade below A detected!" && exit 1 || echo "All MI grades are A."
          radon hal {} --exclude "scratch" -s | awk "/effort/ { if (\$3 > 2000) print FILENAME \": High Halstead effort:\" \$3 }"
          radon hal {} --exclude "scratch" -s | awk "/difficulty/ { if (\$3 > 10) print FILENAME \": High Halstead difficulty:\" \$3 }"'
        language: system
        files: \.py$
        exclude: ^scratch/
