repos:
  # Python hooks
  - repo: local
    hooks:
      # Ruff for Python linting
      - id: ruff
        name: ruff (Python linting)
        entry: ruff check --fix
        language: python
        types_or: [python, pyi, jupyter]
        files: \.py$

      # Ruff for Python formatting
      - id: ruff-format
        name: ruff-format (Python formatting)
        entry: ruff format
        language: python
        types_or: [python, pyi, jupyter]
        files: \.py$

      # Mypy for Python type checks
      - id: mypy
        name: mypy (Python typing)
        entry: mypy .
        language: python
        types_or: [python, pyi]
        files: \.py$

      # Dependency checks for Python
      - id: check-python-dependencies
        name: Check Python dependencies
        entry: bash -c 'pipenv check --bare --quiet || (echo "Python dependencies check failed" && exit 1)'
        language: system
        files: ^Pipfile$
