version: '3'
services:
  formatter:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app
    command: sh -c "pip install ruff && ruff format"
    network_mode: 'host'

  linter:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app
    command: sh -c "pip install ruff && ruff check --fix"
    network_mode: 'host'

  climate:
    build:
      context: .
    volumes:
      - ./src:/usr/src/app
    stdin_open: true  # Allows interactive input
    tty: true  # Allocates a pseudo-TTY for bash
    network_mode: 'host'
