services:
  formatter:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: sh -c "pip install ruff && ruff format"
    network_mode: 'host'

  linter:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: sh -c "pip install ruff && ruff check --fix"
    network_mode: 'host'

  climate:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - ~/.config/gcloud/application_default_credentials.json:/usr/src/app/credentials/service-account-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/credentials/service-account-key.json
    stdin_open: true
    tty: true
    network_mode: 'host'
    # Automatically run bash inside the pipenv environment
    command: ["pipenv", "run", "bash"]
