[tool.poetry]
name = "pop_vulnerability"
version = "0.1.0"
description = "Population vulnerability for HotspotStoplight project"
authors = ["Nissim Lebovits"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"  # Specify the desired Python version here
geemap = "^0.29.6"
wxee = "^0.4.1"
ipykernel = "^6.27.1"
gdown = "^4.7.1"
folium = "^0.15.1"
pyproj = "^3.6.1"
rio-cogeo = "^5.1.1"
earthengine-api = "^0.1.388"
openpyxl = "^3.1.2"
pygeoboundaries = "^0.0.2"
geopandas = "^0.14.3"
geojson = "^3.1.0"
requests-cache = "^1.1.1"
colorcet = "^3.0.1"
matplotlib = "^3.8.2"
holoviews = "^1.18.2"
xarray = "^2024.1.1"
xee = "^0.0.8"
fuzzywuzzy = "^0.18.0"
python-levenshtein = "^0.25.0"
black = "^24.3.0"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
