name: PR Checks

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Set the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Run Ruff linter
        run: |
          ruff check --fix

      - name: Run Ruff formatter
        run: |
          ruff format

      - name: Run mypy type checks
        run: |
          mypy .
