name: PR Checks

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies for linting
        run: |
          python -m pip install --upgrade pip
          pip install ruff pylint

      - name: Run Ruff linter
        run: |
          ruff check --fix
        continue-on-error: true

      - name: Run Pylint duplicate code check
        run: |
          pylint --disable=all --enable=duplicate-code --ignore=scratch/ -sn .
        continue-on-error: true

      - name: Run Vulture dead code check
        uses: gtkacz/vulture-action@1.0.0
        with:
          args: '--min-confidence 60 --exclude "scratch/"'
        continue-on-error: true

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies for type checking
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy type checks
        run: |
          mypy .
        continue-on-error: true

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker container
        run: |
          docker compose build --parallel
